server {
    listen 80;
    server_name codyssey.duckdns.org;

    root /usr/share/nginx/html;
    index index.html;
}

server {
    listen 443 ssl;
    server_name codyssey.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/codyssey.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/codyssey.duckdns.org/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /usr/share/nginx/html;
    index index.html;
}
